version: '3.7'
services:

  docker_mongo:
    restart: always
    image: mongo:latest
      - "127.0.0.1:27017:27017"

  docker_redis:
    restart: always
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data

  webapp_next:
    restart: always
    build:
      context: webapp/
      args:
        - GOOGLE_KEYPATH=keyfile.json
        - SHORT_COMMIT_HASH=${SHORT_COMMIT_HASH}
        - NEXT_PUBLIC_NO_PAYMENT_REQUIRED=1
        - NEXT_PUBLIC_ENABLE_GOOGLE_OAUTH=
        - NEXT_PUBLIC_ENABLE_GITHUB_OAUTH=
        - POSTHOG_KEY=
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - docker_mongo
      - docker_redis
    environment:
      - NODE_ENV=development
      - DB_URL=mongodb://docker_mongo:27017/test
      - REDIS_HOST=docker_redis
      - REDIS_PASS=
      - JWT_SECRET=changeme
      - COOKIE_SECRET=changeme
      - AGENT_BACKEND_SOCKET_TOKEN=changeme
      - PROJECT_ID=
      - FROM_EMAIL_ADDRESS=noreply@agentcloud.dev
      - URL_APP=http://localhost:3000
      - DEBUG=webapp:*
      - STRIPE_WEBHOOK_SECRET=
      - STRIPE_ACCOUNT_SECRET=
      - NEXT_PUBLIC_NO_PAYMENT_REQUIRED=1
      - OAUTH_GITHUB_CLIENT_ID=
      - OAUTH_GITHUB_CLIENT_SECRET=
      - OAUTH_GOOGLE_CLIENT_ID=
      - OAUTH_GOOGLE_CLIENT_SECRET=
  agent_backend:
    restart: always
    build:
      context: agent-backend/
      args:
        - SHORT_COMMIT_HASH=${SHORT_COMMIT_HASH}
    ports:
      - '127.0.0.1:8080:8080'
    image: agent_backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOCAL=True
      - MAX_THREADS=50
      - OAI_CONFIG_LIST=/app/config/OAI_CONFIG_LIST.json
      - BASE_PATH=/app
      - SOCKET_URL=http://webapp_next:3000/
      - DB_URL=mongodb://docker_mongo:27017/test
      - REDIS_HOST=docker_redis
      - MONGO_DB_NAME=test
      - OPENAI_API_KEY=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
      - MAX_RETRIES=10
      - AGENT_BACKEND_SOCKET_TOKEN=changeme

volumes:
  mongodb_data_container:
  redis_data:
